### ISSUE TITLE
Follow up question to #26

### ISSUE THREAD

**Issue by MichaelWerner** [breuerfelix/chromedriver-py#31] opened 2023-08-20 23:56 UTC
Hello,

great that it works with cx_freeze.
I like pyinstaller because it creates a single executable.
Do you have any plans to fix this problem?

thanks,

Michael

**Comment by breuerfelix** [comment] 2023-08-21 09:48
Hey,
do you have some example repo that i can reproduce and see the errors? Maybe with some Readme so i can follow the instructions?
I never used pyinstaller now cx_freeze myself. It would be best to know your use case.

That way i can investigate if this is actually fixable or if pyinstaller just won't let you bundle other binaries :)

**Comment by MichaelWerner** [comment] 2023-08-22 01:22
Hi Felix,

here is the script.
https://github.com/MichaelWerner/Python/blob/master/scrape_nfl.py

Thanks,

Michael

**Comment by breuerfelix** [comment] 2023-08-31 15:26
Hey Michael,
I am sorry to say but bundling this into one binary is not possible, because it would need to bundle the chromedriver binary INTO the python binary. And what is the path to the Chromedriver binary then? It would be somehow merged into the program binary. So for the chromedriver there is nothing that it could start.
This is also the reason why programs install into a Folder and have multiple files (lets say, one reason, not the only reason)

So yeah, bundling this package into a single executable won't ever work, sadly.
I will close this Issue but just comment on it if you have more questions regarding this topic :)

**Closed by breuerfelix** 2023-08-31 15:26 UTC
